# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.TextField(default='admin@admin'),
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.TextField(default='sans_nom'),
        ),
    ]
