# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0002_auto_20170920_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.CharField(default='admin@admin', error_messages=set(['rs']), max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(default='toto', error_messages=set(['rs']), max_length=20),
        ),
    ]
