# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0003_auto_20170920_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.CharField(default='admin@admin', max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(default='toto', max_length=20),
        ),
    ]
